export const SEARCH_POKEMOM = 'SEARCH_POKEMOM';
export const SEARCH_POKEMOM_COMPLETE = 'SEARCH_POKEMOM_COMPLETE';
export const SEARCH_POKEMOM_BY_NAME = 'SEARCH_POKEMOM_BY_NAME';
export const SEARCH_POKEMOM_BY_NAME_COMPELETE = 'SEARCH_POKEMOM_BY_NAME_COMPELETE';